name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'v1.18.2-k3s1'
      - run: |
          kubectl get nodes
          kubectl version
